apiVersion: apps/v1
kind: Deployment
metadata:
  name: crm-backend
  labels:
    {{- include "crm.labels" . | nindent 4 }}
    app: crm-backend
spec:
  replicas: {{ .Values.backend.replicas }}
  selector:
    matchLabels:
      app: crm-backend
  template:
    metadata:
      labels:
        {{- include "crm.labels" . | nindent 8 }}
        app: crm-backend
    spec:
      containers:
        - name: backend
          image: {{ .Values.backend.image }}
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: {{ .Values.backend.port }}
          env:
            - name: SPRING_DATASOURCE_URL
              value: "jdbc:postgresql://crm-postgres:5432/{{ .Values.postgres.db }}"
            - name: SPRING_DATASOURCE_USERNAME
              value: {{ .Values.postgres.user | quote }}
            - name: SPRING_DATASOURCE_PASSWORD
              value: {{ .Values.postgres.password | quote }}
