apiVersion: apps/v1
kind: Deployment
metadata:
  name: crm-frontend
  labels:
    {{- include "crm.labels" . | nindent 4 }}
    app: crm-frontend
spec:
  replicas: {{ .Values.frontend.replicas }}
  selector:
    matchLabels:
      app: crm-frontend
  template:
    metadata:
      labels:
        {{- include "crm.labels" . | nindent 8 }}
        app: crm-frontend
    spec:
      imagePullSecrets:
        - name: ghcr-secret
      containers:
        - name: frontend
          image: "{{ .Values.frontend.image.repository }}:{{ .Values.frontend.image.tag }}"
          imagePullPolicy: {{ .Values.frontend.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.frontend.port }}
            - name: nginx-status
              containerPort: 8080
        - name: nginx-exporter
          image: nginx/nginx-prometheus-exporter:1.3.0
          args:
            - "-nginx.scrape-uri=http://localhost:8080/nginx_status"
          ports:
            - name: metrics
              containerPort: 9113
