apiVersion: apps/v1
kind: Deployment
metadata:
  name: crm-frontend
  labels:
    {{- include "crm.labels" . | nindent 4 }}
    app: crm-frontend
spec:
  replicas: {{ .Values.frontend.replicas }}
  selector:
    matchLabels:
      app: crm-frontend
  template:
    metadata:
      labels:
        {{- include "crm.labels" . | nindent 8 }}
        app: crm-frontend
    spec:
      containers:
        - name: frontend
          image: {{ .Values.frontend.image }}
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: {{ .Values.frontend.port }}
