apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: crm-postgres
  namespace: default
  labels:
    {{- include "crm.labels" . | nindent 4 }}
    release: monitoring
spec:
  selector:
    matchLabels:
      app: crm-postgres
  endpoints:
    - port: metrics
      path: /metrics
      interval: 15s
