apiVersion: apps/v1
kind: Deployment
metadata:
  name: crm-postgres
  labels:
    {{- include "crm.labels" . | nindent 4 }}
    app: crm-postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: crm-postgres
  template:
    metadata:
      labels:
        {{- include "crm.labels" . | nindent 8 }}
        app: crm-postgres
    spec:
      containers:
        - name: postgres
          image: {{ .Values.postgres.image }}
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              value: {{ .Values.postgres.db | quote }}
            - name: POSTGRES_USER
              value: {{ .Values.postgres.user | quote }}
            - name: POSTGRES_PASSWORD
              value: {{ .Values.postgres.password | quote }}
          volumeMounts:
            - name: postgres-storage
              mountPath: /var/lib/postgresql/data
              subPath: postgres
        - name: postgres-exporter
          image: quay.io/prometheuscommunity/postgres-exporter:v0.15.0
          ports:
            - name: metrics
              containerPort: 9187
          env:
            - name: DATA_SOURCE_URI
              value: "localhost:5432/{{ .Values.postgres.db }}?sslmode=disable"
            - name: DATA_SOURCE_USER
              value: {{ .Values.postgres.user | quote }}
            - name: DATA_SOURCE_PASS
              value: {{ .Values.postgres.password | quote }}
      volumes:
        - name: postgres-storage
          persistentVolumeClaim:
            claimName: crm-postgres-pvc
