spring.datasource.url=jdbc:postgresql://localhost:5432/crmdb
spring.datasource.username=crmuser
spring.datasource.password=crmpassword
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
server.port=8081

management.endpoints.web.exposure.include=health,info,metrics,prometheus
management.endpoint.health.show-details=always

spring.datasource.hikari.max-lifetime=270000
spring.datasource.hikari.connection-timeout=20000
spring.datasource.hikari.validation-timeout=5000
