{{- if .Values.postgres.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.name }}-postgres
  namespace: default
  labels:
    {{- include "golden-path-service.labels" . | nindent 4 }}
    app: {{ .Values.name }}-postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.name }}-postgres
  template:
    metadata:
      labels:
        {{- include "golden-path-service.labels" . | nindent 8 }}
        app: {{ .Values.name }}-postgres
    spec:
      containers:
        - name: postgres
          image: {{ .Values.postgres.image }}
          ports:
            - name: postgres
              containerPort: 5432
          env:
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.name }}-postgres
                  key: POSTGRES_DB
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.name }}-postgres
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.name }}-postgres
                  key: POSTGRES_PASSWORD
          resources:
            {{- toYaml .Values.postgres.resources | nindent 12 }}
          volumeMounts:
            - name: postgres-storage
              mountPath: /var/lib/postgresql/data
              subPath: postgres

        - name: postgres-exporter
          image: quay.io/prometheuscommunity/postgres-exporter:v0.15.0
          ports:
            - name: metrics
              containerPort: 9187
          env:
            - name: DATA_SOURCE_URI
              value: "localhost:5432/{{ .Values.postgres.db }}?sslmode=disable"
            - name: DATA_SOURCE_USER
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.name }}-postgres
                  key: POSTGRES_USER
            - name: DATA_SOURCE_PASS
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.name }}-postgres
                  key: POSTGRES_PASSWORD

      volumes:
        - name: postgres-storage
          persistentVolumeClaim:
            claimName: {{ .Values.name }}-postgres-pvc
{{- end }}
