apiVersion: scaffolder.backstage.io/v1beta3
kind: Template

metadata:
  name: golden-path-service
  title: Golden Path Service
  description: Create a production-ready Angular + Spring Boot + PostgreSQL service
  tags:
    - recommended
    - angular
    - spring-boot
    - postgresql
    - kubernetes

spec:
  owner: group:default/guests
  type: service

  parameters:
    - title: Service Information
      required:
        - name
        - description
      properties:
        name:
          title: Service Name
          type: string
          description: Name of the service
          pattern: '^[a-z0-9-]+$'

        description:
          title: Description
          type: string
          description: Short description of the service

  steps:
    - id: fetch
      name: Fetch Golden Path Skeleton
      action: fetch:template
      input:
        url: ./skeleton
        copyWithoutTemplating:
          - .github/workflows/**
        values:
          name: ${{ parameters.name }}
          description: ${{ parameters.description }}
          githubOwner: FatmaMejri1

    - id: publish
      name: Publish GitHub Repository
      action: publish:github
      input:
        repoUrl: github.com?owner=FatmaMejri1&repo=${{ parameters.name }}
        description: ${{ parameters.description }}
        defaultBranch: main
        repoVisibility: private
        secrets:
          GHCR_PAT: ${{ secrets.USER_OAUTH_TOKEN || secrets.GITHUB_TOKEN }}

    - id: set-workflow-permissions
      name: Configure GitHub Actions Workflow Permissions (Automated Platform Policy)
      action: http:backstage:request
      continueOnError: true
      input:
        method: PUT
        path: /proxy/github/api/repos/FatmaMejri1/${{ parameters.name }}/actions/permissions/workflow
        headers:
          content-type: application/json
        body:
          default_workflow_permissions: write
          can_approve_pull_request_reviews: true

    - id: register
      name: Register Component
      action: catalog:register
      input:
        repoContentsUrl: ${{ steps.publish.output.repoContentsUrl }}
        catalogInfoPath: /catalog-info.yaml

  output:
    links:
      - title: Repository
        url: ${{ steps.publish.output.remoteUrl }}

      - title: Open in Catalog
        icon: catalog
        entityRef: ${{ steps.register.output.entityRef }}
