{{- if and .Values.monitoring.enabled .Values.monitoring.serviceMonitor.enabled .Values.backend.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ .Values.name }}-backend
  namespace: default
  labels:
    {{- include "golden-path-service.labels" . | nindent 4 }}
    release: monitoring
spec:
  selector:
    matchLabels:
      app: {{ .Values.name }}-backend
  endpoints:
    - port: http
      path: /actuator/prometheus
      interval: {{ .Values.monitoring.serviceMonitor.interval }}
{{- end }}
