{{- if .Values.backend.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.name }}-backend
  namespace: default
  labels:
    {{- include "golden-path-service.labels" . | nindent 4 }}
    app: {{ .Values.name }}-backend
spec:
  type: ClusterIP
  selector:
    app: {{ .Values.name }}-backend
  ports:
    - name: http
      port: {{ .Values.backend.port }}
      targetPort: http
{{- end }}
