kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: idp-backstage

nodes:
  - role: control-plane
    extraPortMappings:
      - containerPort: 30007
        hostPort: 7007
        protocol: TCP
      - containerPort: 30080
        hostPort: 8080
        protocol: TCP
      - containerPort: 30300
        hostPort: 3300
        protocol: TCP

  - role: worker

  - role: worker
