replicaCount: 1
image:
  repository: ghcr.io/fatmamejri1/${{ values.name }}
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8001

ingress:
  enabled: true
  className: nginx
  path: /ai

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 100m
    memory: 128Mi
